version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: frontend
    volumes:
      - static:/app/build
    
  nginx-react:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx-react
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - frontend
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:rov
      - static:/usr/share/nginx/html/

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static:
    