# CircleCI configuration file
version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  aws-ecr: circleci/aws-ecr@8.1.2 # use the AWS ECR orb
  aws-ecs: circleci/aws-ecs@3.2.0 # use the AWS ECS orb
  aws-cli: circleci/aws-cli@3.1.1 # use the AWS CLI orb

executors:
  frontend-executor:
    docker:
      - image: cimg/node:18.5

jobs:
  # Job one with a unique name
  test-frontend:
    executor: frontend-executor
    environment:
      DEBUG: 1
      API_HOST: localhost
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test -- --coverage --watchAll=false
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage/lcov-report

  build-and-push-frontend:
    executor: docker/docker
    environment:
      DEBUG: 1
      API_HOST: localhost
      DOCKER_IMAGE: waflol/social-media-fe
      DOCKER_TAG: lastest
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - run:
          name: docker/build
          command: |
            docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  build-and-push-ecr:
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
workflows:
  # Name of workflow
  pipeline:
    # List of jobs that will run
    jobs:
      - test-frontend
      - build-and-push-frontend:
          requires:
            - test-frontend
          # filters:
          #   branches:
          #     only:
          #       - main
      # - aws-ecr/build-and-push-image: 
      #     requires:
      #       - test-frontend
      #     dockerfile: Dockerfile
      #     path: .
      #     profile-name: waflol
      #     repo: social-web-api
      #     tag: latest
