# CircleCI configuration file
version: 2.1
orbs:
  docker: circleci/docker@2.2.0

executors:
  frontend-executor:
    docker:
      - image: cimg/node:16.13

jobs:
  # Job one with a unique name
  test-frontend:
    executor: frontend-executor
    environment:
      DEBUG: 1
      API_HOST: localhost
    steps:
      - checkout
      - run:
          name: npm-install
          command: npm install
      - run:
          name: Run tests
          command: npm run test -- --coverage --watchAll=false
      - store_artifacts:
          path: coverage

  deploy-prod:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "59:49:79:51:6d:cc:b8:d1:17:b6:2f:af:cd:ea:12:15"
      - run: ssh $DROPLET_USER@$DROPLET_IP "./deploy.sh"

  deploy-prod-2:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "59:49:79:51:6d:cc:b8:d1:17:b6:2f:af:cd:ea:12:15"
      - run: ssh $DROPLET_USER_2@$DROPLET_IP_2 "./deploy.sh"
  

workflows:
  # Name of workflow
  frontend-pipeline:
    # List of jobs that will run
    jobs:
      - test-frontend
      - deploy-prod:
          requires:
            - test-frontend
          filters:
            branches:
              only:
                - main
      - deploy-prod-2:
          requires:
            - test-frontend
          filters:
            branches:
              only:
                - deploy/kltndemo